### ISSUE TITLE
자바스크립트 → 타입스크립트로 변환

### ISSUE THREAD

**Issue by park-daeun** [GyeongSoTone/danplay-frontend#16]
## 🏷 기능 설명

- 자바스크립트 코드를 타입스크립트로 변환합니다.

## ✔️ to-do

- [x] 타입스크립트 환경 설정 및 ts 파일로 변환
- [x] `any` 타입 선언
- [x] `any` 타입을 더 적절한 타입으로 변경
