### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by park-daeun** [GyeongSoTone/danplay-frontend#3]
## 🏷 기능 설명

- Header 마크업 및 기능 구현

## ✔️ to-do

- [x] 로고 클릭 시 메인 페이지로 이동

- [x] user 아이콘

  - [x] 로그인 X - 로그인 페이지로 이동
  - [x] 로그인 O - 내정보 페이지로 이동
 
- [x] more 아이콘
